server:
  port: 8081
  servlet:
    encoding:
      force-response: true

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${db.url:jdbc:oracle:thin:@localhost:1521/demo}
    username: ${db.username:SYSTEM}
    password: ${db.password:root}
    hikari:
      connectionTimeout: 10000
      idleTimeout: 600000
      maximum-pool-size: 300
      minimum-idle: 5
      maxLifetime: 100000
      leak-detection-threshold: 2000
  sql:
    init:
      mode: never

  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration/v1

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.example.domain
  configuration:
    map-underscore-to-camel-case: true
    call-statement-runnable: true

logging:
  level:
    org.mybatis.spring.SqlSession: debug
    com.example.infrastructure.article.persistence: debug
    org.apache.ibatis: DEBUG
    org.mybatis.spring: DEBUG